# Generated by Django 4.2.7 on 2025-10-18 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(max_length=10, verbose_name='Icône (emoji)')),
                ('gradient', models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', max_length=200, verbose_name='Dégradé CSS')),
                ('services', models.JSONField(default=list, help_text='Liste des services au format JSON', verbose_name='Services (JSON)')),
                ('kpis', models.JSONField(default=list, help_text='Liste des KPI au format JSON', verbose_name='KPI (JSON)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise/Organisation')),
                ('service', models.CharField(blank=True, choices=[('gss', 'Global Songhoy Services (GSS)'), ('sogis', 'Sogis - Immobilier'), ('golden', 'Société Golden - Transport'), ('angnie', 'Angnie Mali - Propreté'), ('autre', 'Autre')], max_length=10, null=True, verbose_name='Service concerné')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('traite', 'Traité')], default='nouveau', max_length=10, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('excerpt', models.TextField(blank=True, help_text="Court résumé de l'article (optionnel)", max_length=300, verbose_name='Extrait')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, help_text="Alternative à l'upload d'image", null=True, verbose_name="URL de l'image")),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('featured', models.BooleanField(default=False, verbose_name='Article en vedette')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('company', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('rating', models.IntegerField(default=5, help_text='Note de 1 à 5 étoiles', verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
