# Generated by Django 4.2.7 on 2025-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Description complète des domaines clés et KPI', verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Description courte'),
        ),
        migrations.CreateModel(
            name='CompanyProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_projects/', verbose_name='Image du projet')),
                ('title', models.CharField(help_text='Nom ou description du projet', max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description du projet')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='website.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projets',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
