# Generated by Django 4.2.7 on 2025-10-19 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_company_detailed_description_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AZI GROUP', max_length=200, verbose_name='Titre principal')),
                ('subtitle', models.TextField(default="Excellence Opérationnelle au Service de l'Impact en Afrique de l'Ouest", verbose_name='Sous-titre')),
                ('background_image', models.ImageField(help_text='Image qui apparaîtra en arrière-plan de la section hero', upload_to='homepage/', verbose_name='Image de fond')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='Valeur entre 0 (transparent) et 1 (opaque)', verbose_name="Opacité de l'overlay")),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour masquer cette section', verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Section Hero de la page d'accueil",
                'verbose_name_plural': "Sections Hero de la page d'accueil",
                'ordering': ['-created_at'],
            },
        ),
    ]
