# Generated by Django 4.2.7 on 2025-10-19 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepagehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AZI GROUP', max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(help_text='Logo qui apparaîtra dans la barre de navigation', upload_to='navigation/', verbose_name='Logo de navigation')),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour masquer ce logo', verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Logo de navigation',
                'verbose_name_plural': 'Logos de navigation',
                'ordering': ['-created_at'],
            },
        ),
    ]
