# Generated by Django 5.2.7 on 2025-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_navigationlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, choices=[('azi_group', 'AZI GROUP'), ('gss', 'Global Songhoy Services (GSS)'), ('sogis', 'Sogis - Immobilier'), ('golden', 'Société Golden - Transport'), ('angnie', 'Angnie Mali - Propreté')], max_length=10, null=True, verbose_name='Service concerné'),
        ),
    ]
