# Generated by Django 4.2.27 on 2026-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, choices=[('azi_group', 'IBC SARL'), ('gss', 'Global Songhoy Services (GSS)'), ('sogis', 'Sogis - Immobilier'), ('golden', 'Société Golden - Transport'), ('angnie', 'Angnie Mali - Propreté')], max_length=10, null=True, verbose_name='Service concerné'),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='title',
            field=models.CharField(default='IBC Sarl BTP', max_length=200, verbose_name='Titre principal'),
        ),
        migrations.AlterField(
            model_name='navigationlogo',
            name='name',
            field=models.CharField(default='IBC Sarl BTP', max_length=100, verbose_name="Nom de l'entreprise"),
        ),
    ]
