# Generated by Django 4.2.27 on 2026-01-20 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contact_service_alter_homepagehero_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.news', verbose_name='Actualité')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
