# Generated by Django 4.2.27 on 2026-01-20 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('realise', 'Réalisé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Client')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('contract_details', models.TextField(blank=True, verbose_name='Ensemble de contrats')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name="Durée d'exécution")),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date de fin / Livraison')),
                ('completion_info', models.TextField(blank=True, verbose_name='Info sur la fin de réalisation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image principale')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='website.company', verbose_name='Entreprise responsable')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projet',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
