# Generated by Django 4.2.27 on 2026-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_project_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.company', verbose_name='Partenaires'),
        ),
    ]
