# Generated by Django 6.0.1 on 2026-01-21 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_project_company_project_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.TextField(blank=True, verbose_name='Sous-titre')),
                ('image', models.ImageField(help_text='Image de fond du slide (format large recommandé)', upload_to='homepage/slides/', verbose_name='Image')),
                ('overlay_opacity', models.FloatField(default=0.45, help_text='Valeur entre 0 (transparent) et 1 (opaque)', verbose_name="Opacité de l'overlay")),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='Texte du bouton')),
                ('button_url', models.CharField(blank=True, help_text='Ex: /projects/ ou https://...', max_length=300, verbose_name='Lien du bouton')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Slide d'accueil",
                'verbose_name_plural': "Slides d'accueil",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
