# Generated by Django 6.0.1 on 2026-01-22 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_homepageslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Lomé, Togo', help_text="Adresse complète de l'entreprise", max_length=200, verbose_name='Adresse')),
                ('address_details', models.CharField(blank=True, default='Quartier administratif', help_text="Complément d'adresse (quartier, etc.)", max_length=200, verbose_name="Détails de l'adresse")),
                ('email', models.EmailField(default='contact@ibcbtp.tg', max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(default='+228 XX XX XX XX', help_text='Format: +228 XX XX XX XX', max_length=20, verbose_name='Téléphone')),
                ('hours', models.CharField(default='Lundi – Vendredi : 8h00 – 18h00', max_length=200, verbose_name="Horaires d'ouverture")),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour masquer ces informations', verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Information de contact',
                'verbose_name_plural': 'Informations de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, choices=[('azi_group', 'IBC SARL BTP'), ('gss', 'Global Songhoy Services (GSS)'), ('sogis', 'Sogis - Immobilier'), ('golden', 'Société Golden - Transport'), ('angnie', 'Angnie Mali - Propreté')], max_length=10, null=True, verbose_name='Service concerné'),
        ),
    ]
