# Generated by Django 6.0.1 on 2026-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contactinfo_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone'),
        ),
    ]
