# Generated by Django 6.0.1 on 2026-01-22 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TG', 'Togo'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('CI', "Côte d'Ivoire"), ('ML', 'Mali'), ('NE', 'Niger'), ('SN', 'Sénégal'), ('GN', 'Guinée'), ('MR', 'Mauritanie'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('CD', 'RD Congo'), ('CG', 'Congo'), ('FR', 'France'), ('BE', 'Belgique'), ('CH', 'Suisse'), ('CA', 'Canada'), ('US', 'États-Unis'), ('OTHER', 'Autre')], help_text='Pays de résidence', max_length=5, verbose_name='Pays')),
                ('phone', models.CharField(help_text='Numéro de téléphone sans indicatif (ex: 90XXXXXX)', max_length=20, verbose_name='Téléphone')),
                ('first_name', models.CharField(help_text="Prénoms de l'utilisateur", max_length=100, verbose_name='Prénoms')),
                ('last_name', models.CharField(help_text="Nom de famille de l'utilisateur", max_length=100, verbose_name='Nom')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
