# Generated by Django 6.0.1 on 2026-01-22 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Chemin visité')),
                ('referer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Référent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de visite')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='website_vis_created_ccdb9a_idx'), models.Index(fields=['ip_address'], name='website_vis_ip_addr_953e88_idx')],
            },
        ),
    ]
