# Generated by Django 6.0.1 on 2026-01-22 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Photo qui s'affichera dans la section 'Qui Sommes-Nous ?' (format carré recommandé)", upload_to='homepage/about/', verbose_name='Photo')),
                ('active', models.BooleanField(default=True, help_text='Désactiver pour masquer cette photo', verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Photo 'Qui Sommes-Nous ?'",
                'verbose_name_plural': "Photos 'Qui Sommes-Nous ?'",
                'ordering': ['-created_at'],
            },
        ),
    ]
